### ISSUE TITLE
Implement Projects

### ISSUE THREAD

**Issue by Taucher2003** [code0-tech/sagittarius#173]
Organizations can have projects.

For now, the projects don't contain anything besides a name and a description.

- [x] Support project creation (https://github.com/code0-tech/sagittarius/pull/174)
- [x] Support project updates (https://github.com/code0-tech/sagittarius/pull/175)
- [x] Support project deletions (https://github.com/code0-tech/sagittarius/pull/176)

**Comment by nicosammito** [comment]
@Taucher2003 @Knerio please keep in mind that projects can also be created without a organisation. This is similar to self owned repositories on GitHub that are related to the account.

**Comment by Taucher2003** [comment]
Currently it works as intended. Projects only exist within an organization. We might reconsider that in the future, but for now, it definitely isn't worth the added complexity to having projects within two different parent types.

One example of the added complexity would be members. Either you can't invite anyone to your personal projects or we would have to introduce members at a project level and then somehow combine it with the members on organization level when the project is in an organization. And if we would be to support members on project level, either all members are project administrators or we would also have to introduce roles on the project level which would have to be properly merged with organization roles for projects in organizations.

For now I would prefer that projects stay in organizations and if a user wants personal projects, they can create an organization just for themself.
